### ISSUE TITLE
maxLoad or maxWeight?

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-routes#43]
Currently the REM uses 'maxLoad', but 'maxWeight' seems to be more common (e.g. in OSM). 

It is also 'weight' in the API.

**Comment by rphillips3** [comment]
The OGC API suite should be as internally consistent as possible, so I think consistency between the API and REM is critical, so 'weight' should replace 'load' where applicable. 

A happy accident if that aligns with a chosen data set used (OSM in this case), otherwise it's just a mapping exercise for the dev using the API/REM.

**Comment by cportele** [comment]
Meeting 2021-12-09: Agreement to use "weight" consistently.
